### ISSUE TITLE
Styling broken when scrolling horizontally

### ISSUE THREAD

**Issue by rhaberkorn** [orbitalquark/scinterm#11]
This is Jinx built from c29125950e33f1dd02473888cdf9b6a1959442c9 with [Scintilla 5.1.3](https://github.com/rhaberkorn/scintilla-mirror/commit/fab670c471c7eea28d43ebaeed14b3c886e2c6e5):

![2021-10-19-234144_294x133_scrot](https://user-images.githubusercontent.com/540361/137987415-9d83034f-a39f-4848-8371-a6775fdb454f.png)

I made the window small enough, so I can horizontally scroll line 3. But this happens with large windows as well. Whenever scrolling horizontally, the stylings appear to be messed up.

**Comment by orbitalquark** [comment]
Thanks for the report. I have also seen this randomly. I'll look into it when I have some time.

**Comment by orbitalquark** [comment]
Fixed via https://github.com/orbitalquark/scinterm/commit/3fec80f7db830af23fdb3f97e5ba9c222af711cc
