### ISSUE TITLE
Building broken on Mac OS 12

### ISSUE THREAD

**Issue by rhaberkorn** [orbitalquark/scinterm#24]
See for instance: https://github.com/rhaberkorn/sciteco/actions/runs/11414224313/job/31762843710#step:6:214

`A_ITALIC` is not available on the ancient ncurses shipping with Mac OS 12. In fact, `A_ITALIC` is a non-X/Open extension according to curs_attr(3X). You need to `#ifdef` any reference to it.
(I didn't know that either!)

**Comment by rhaberkorn** [comment]
While you're at it, there are warnings because `sprintf()` is deprecated. Probably not only on Mac OS. This can easily be avoided by using `snprintf()` instead.

**Comment by orbitalquark** [comment]
Thanks, I noticed this a couple days ago and it's fixed in https://github.com/orbitalquark/scinterm/commit/60e32993f7d31674aa9b8db0766d9f6984fb4891.

**Comment by rhaberkorn** [comment]
Oops, didn't even see you committed it in the meantime.
